name: Release

on:
  push:
    tags:
      - 'v**'

permissions:
  contents: write

env:
  BUILD_TYPE: Release

jobs:
  build-breadcrumb_linux-shared_x86-64:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Download and Compile Libraries
        run: ./script/library.sh SHARED 2

      - name: Configure Breadcrumb
        run: cmake -B build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DSTATIC=OFF

      - name: Build Breadcrumb
        run: cmake --build build --parallel 2 --verbose

      - name: Rename Binaries
        run: |
          mv bin/mandelbrot bin/mandelbrot_linux-shared_x86-64
          mv bin/mersenne bin/mersenne_linux-shared_x86-64

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-shared
          path: |
            bin/mandelbrot_linux-shared_x86-64
            bin/mersenne_linux-shared_x86-64

  build-breadcrumb_linux-static_x86-64:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Download and Compile Libraries
        run: ./script/library.sh STATIC 2

      - name: Configure Breadcrumb
        run: cmake -B build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DSTATIC=ON

      - name: Build Breadcrumb
        run: cmake --build build --parallel 2 --verbose

      - name: Rename Binaries
        run: |
          mv bin/mandelbrot bin/mandelbrot_linux-static_x86-64
          mv bin/mersenne bin/mersenne_linux-static_x86-64

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-static
          path: |
            bin/mandelbrot_linux-static_x86-64
            bin/mersenne_linux-static_x86-64

  release:
    runs-on: ubuntu-latest
    needs: [build-breadcrumb_linux-shared_x86-64, build-breadcrumb_linux-static_x86-64]

    steps:
      - uses: actions/checkout@v4

      - name: Download Artifacts
        uses: actions/download-artifact@v4

      - name: Create x86-64 Linux Shared Packages
        run: |
          cp linux-shared/mandelbrot_linux-shared_x86-64 mandelbrot
          cp linux-shared/mersenne_linux-shared_x86-64 mersenne
          tar -czf breadcrumb_linux-shared_x86-64.tar.gz mandelbrot mersenne LICENSE.md

      - name: Create x86-64 Linux Static Packages
        run: |
          cp linux-static/mandelbrot_linux-static_x86-64 mandelbrot
          cp linux-static/mersenne_linux-static_x86-64 mersenne
          tar -czf breadcrumb_linux-static_x86-64.tar.gz mandelbrot mersenne LICENSE.md

      - name: Release linux-shared_x86-64 Version of Breadcrumb
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{secrets.GITHUB_TOKEN}}
          file: breadcrumb_linux-shared_x86-64.tar.gz
          tag: ${{github.ref}}

      - name: Release linux-static_x86-64 Version of Breadcrumb
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{secrets.GITHUB_TOKEN}}
          file: breadcrumb_linux-static_x86-64.tar.gz
          tag: ${{github.ref}}
